CREATE TABLE IF NOT EXISTS user_invitations (
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    expiry TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);