
FROM golang:1.25-alpine3.23 AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o ./bin/main ./cmd/api

FROM alpine:3.23
RUN adduser -D -u 10001 appuser
COPY --from=build /src/bin/main /main
USER appuser
# EXPOSE 8080
ENTRYPOINT [ "/main" ]
